"""Autogeneración de customerCode (al crear) y apiKey (al otorgar servicio)."""

from app.security.service_codes import SERVICE_BHE

ADMIN = {"X-Admin-Key": "test-admin-key-0123456789"}


def test_create_customer_autogenerates_key(client, db):
    r = client.post(
        "/admin/customers",
        json={"name": "Grupo Los Lirios", "rut": "76158145-7", "environment": "CERTIFICATION"},
        headers=ADMIN,
    )
    assert r.status_code == 200, r.text
    key = r.json()["key"]
    # Código opaco: no deriva del nombre y es corto/URL-safe.
    assert "lirios" not in key.lower()
    assert 8 <= len(key) <= 24


def test_create_customer_respects_explicit_key(client, db):
    r = client.post(
        "/admin/customers",
        json={"name": "X", "key": "mi-codigo", "rut": "76158145-7"},
        headers=ADMIN,
    )
    assert r.status_code == 200, r.text
    assert r.json()["key"] == "mi-codigo"


def test_autogenerated_keys_are_unique(client, db):
    keys = set()
    for _ in range(3):
        r = client.post(
            "/admin/customers", json={"name": "Repetido", "rut": "76158145-7"}, headers=ADMIN
        )
        assert r.status_code == 200, r.text
        keys.add(r.json()["key"])
    assert len(keys) == 3  # sufijo aleatorio evita colisiones


def test_grant_autogenerates_apikey(client, db):
    cid = client.post(
        "/admin/customers", json={"name": "Y", "rut": "76158145-7"}, headers=ADMIN
    ).json()["id"]
    g = client.post(
        f"/admin/customers/{cid}/services", json={"service_code": SERVICE_BHE}, headers=ADMIN
    )
    assert g.status_code == 200, g.text
    body = g.json()
    assert body["granted"] is True
    assert body["apikey"]  # generada y devuelta una vez


def test_grant_keeps_provided_apikey_secret(client, db):
    cid = client.post(
        "/admin/customers", json={"name": "Z", "rut": "76158145-7"}, headers=ADMIN
    ).json()["id"]
    g = client.post(
        f"/admin/customers/{cid}/services",
        json={"service_code": SERVICE_BHE, "apikey": "mi-secreto"},
        headers=ADMIN,
    )
    assert g.status_code == 200, g.text
    # Si el cliente la envió, no la devolvemos (ya la conoce).
    assert g.json()["apikey"] is None
