"""init schema

Revision ID: acde811a7ebc
Revises: 
Create Date: 2026-06-09 11:08:19.934453

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acde811a7ebc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.Enum('CERTIFICATION', 'PRODUCTION', name='siienvironment'), nullable=False),
    sa.Column('resolution_number', sa.Integer(), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_key'), 'customer', ['key'], unique=True)
    op.create_index(op.f('ix_customer_rut'), 'customer', ['rut'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_code'), 'service', ['code'], unique=True)
    op.create_table('caf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Integer(), nullable=False),
    sa.Column('folio_from', sa.Integer(), nullable=False),
    sa.Column('folio_to', sa.Integer(), nullable=False),
    sa.Column('xml_encrypted', sa.String(), nullable=False),
    sa.Column('exhausted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caf_doc_type'), 'caf', ['doc_type'], unique=False)
    op.create_table('customer_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('file_base64', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('apikey_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'service_id')
    )
    op.create_table('folio_pointer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Integer(), nullable=False),
    sa.Column('last_folio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'doc_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folio_pointer')
    op.drop_table('customer_service')
    op.drop_table('customer_request')
    op.drop_table('customer_certificate')
    op.drop_index(op.f('ix_caf_doc_type'), table_name='caf')
    op.drop_table('caf')
    op.drop_index(op.f('ix_service_code'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_customer_rut'), table_name='customer')
    op.drop_index(op.f('ix_customer_key'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
